### ISSUE TITLE
Can't populate react-tinymce-input value after migration to 2.0 version

### ISSUE THREAD

**Issue by CyrilQuandalle** [HurricaneJames/react-tinymce-input#20]
Hi,

I've just updated my react-tinymce-input from 1.2.0 to 2.0 and the prop 'value' can't be populated anymore, my tinyMce stay empty instead of displaying the text from its prop (which I console logged and it wasn't empty). Is there a new way to use it ?

Thanks in advance

**Comment by alysov** [comment]
This is due to change in #14.  See [my comment](/HurricaneJames/react-tinymce-input/pull/14#pullrequestreview-53953081) on that PR.

There's a workaround until a real fix is made: pass in an additional parameter to TinyMCEInput ,`component='textarea'`.  You can see how that parameter is being passed in in [examples/Tiny.js](/HurricaneJames/react-tinymce-input/blob/master/examples/Tiny.js#L45).

Unfortunately, this change made this package unusable as is.

**Comment by CyrilQuandalle** [comment]
Hi,
Thank you very much for this workarround, I was wondering if there was some new configuration to be done on the tinyMce side ;-). I hope it would be fixed soon.

**Comment by HurricaneJames** [comment]
I changed the default to textarea, however the new inline mode does not seem to take the initial value in my example. I do not really use tinymce anymore, and I don't have a tremendous amount of time to debug this new feature. Aside from that, switching to textarea by default seems to fix the default value bug for previously supported cases.

**Comment by CyrilQuandalle** [comment]
Thank you very much, it works ;-)

**Comment by rubizhenko** [comment]
My solution for setting inline editor default value.
In `setupEditor` method add event handler on init
`
editor.on("init", e => {
  editor.setContent(this.props.value);
});
`
now it render initial value properly
